### ISSUE TITLE
Forward OOTF missing in Gamma 2.2-2.6 transforms

### ISSUE THREAD

**Issue by tivikoff** [xtremestuff/protune-transforms#16]
Hey, I noticed that dctl's for conversions to rec 709 gammas (both protune and logb400) are applied without forward OOTF which produces strange gamma curves. It can be fixed with applying second node with "blank" CST and "Apply forward OOTF" checkbox enabled. Idk if this is intentional, just wanted to clarify this. Thanks

"LogB400 -> Gamma 2.4" dctl curve:
![image](https://github.com/user-attachments/assets/25c71639-5a47-4256-b8ef-3b6515f1c6c5)

"LogB400 -> Gamma 2.4" dctl + Blank CST with Forward OOTF:
![image](https://github.com/user-attachments/assets/9eb0714d-3e3d-4267-ab83-b53f6247c77f)

"LogB -> DWG" dctl + CST "DWG -> Gamma 2.4" (Forward OOTF enabled by default):
![image](https://github.com/user-attachments/assets/89dde9bb-7b29-4e0f-b65f-3bd0fa04696f)

**Comment by RikshaDriver** [comment]
This is deliberate.

OOTF / System Gamma is a pandora's box of opinions with a lot of legacy carry-over from the CRT era and CRTs are long since dead. I have very strong opinions about this as an Engineer, but if we stick to the necessity of "OOTF", which value does one use?

For example, do you use Rec.709 with Gamma 2.35 to derive the System Gamma, or do you use the more modern interpretation of BT.1886 (i.e. Gamma 2.4) to define the System Gamma? Or do you take a simplistic approach and apply a 1.2 system gamma to all functions? Or do you relegate this all to the dustbin of history and imply System Gamma of 1 as part of an "artistic" OOTF consideration?

If you consider BT.1886 as the "correct" gamma for OOTF calculations, then you can use the relevant Rec.709 or Gamma 2.4 DCTL to imply the respective forward/reverse OOTF.

Mind you there is no "defined" System Gamma for 2.6 or 2.2, unless you consider the sRGB / Gamma 2.2 relationship to produce the equivalent System Gamma.

**Comment by tivikoff** [comment]
Thank you for the detailed explanation. That makes sense, and it's definitely better to leave this decision to the final user.
Anyway, without OOTF it looks pretty good, without overly deep shadows, so at least artistically I like it better. Thanks again!
